# Generated by Django 4.1.2 on 2022-11-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_dt',
            new_name='created_at',
        ),
    ]
